-- 更新订单表结构，-- 添加缺失字段

ALTER TABLE house_order ADD COLUMN IF NOT EXISTS house_image VARCHAR(500) DEFAULT '';
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS house_address VARCHAR(255) DEFAULT '';
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS house_price DECIMAL(10,2) DEFAULT 0;
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS days INT DEFAULT 30;
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS months INT DEFAULT 1;
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS rent_count INT DEFAULT 1;
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS unit_price DECIMAL(10,2) DEFAULT 0;
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS rent_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS deposit DECIMAL(10,2) DEFAULT 0;
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS guest_name VARCHAR(50) DEFAULT '';
ALTER TABLE house_order ADD COLUMN IF NOT EXISTS guest_phone VARCHAR(11) DEFAULT '';
